-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계
SELECT 
YEAR(SALES_DATE) YEAR, 
MONTH(SALES_DATE) MONTH, 
B.GENDER,
COUNT(DISTINCT A.USER_ID) USERS
FROM ONLINE_SALE A
JOIN USER_INFO B ON A.USER_ID = B.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), B.GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;