-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES 
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS = 'DONE' 
GROUP BY WRITER_ID 
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;